### ISSUE TITLE
Missing @Component or @Configuration on class

### ISSUE THREAD

**Issue by oneturkmen** [vanDusty/SpringBoot-Home#2]
The following class uses `@Bean` on a field, but is missing `@Component` or `@Configuration` annotation on the class. Is it intentional?

https://github.com/vanDusty/SpringBoot-Home/blob/ead464291241006fdaaf050f0ee7c085d780b994/springboot-demo-mybatis-plus/mybatis-plus-demo/src/main/java/cn/van/mybatis/plus/demo/config/MybatisPlusConfig.java#L17

Reference: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Bean.html

**Comment by vanDusty** [comment]
This configuration is intentionally not enabled
